name: b-mertz.com CI
run-name: b-mertz CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - uses: hashicorp/setup-terraform@v2
      - run: |
          npm ci
          npm run build -- --outDir infra/static
        name: Build the application app
      - run: |
          terraform init
          terraform fmt --check
          terraform validate
          terraform plan -var static_dir=static -out plan
        working-directory: infra
        name: Prepare the tf plan
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            infra
            !infra/.terraform*

  deployment:
    runs-on: ubuntu-latest
    # environment: prod
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: |
          terraform init
          terraform apply --auto-approve ./plan
        name: Apply the plan
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
